### ISSUE TITLE
Document search on named vectors

### ISSUE THREAD

**Issue by coszio** [qdrant/docs#113]
We currently only have docs to create a collection with multiple named vectors, but there is no example in the [Search section](https://qdrant.tech/documentation/search/) that uses them. It would be good to add at least one example, such that it is demonstrated how it plays together.
It'd also be good to emphasize that the search can only use one named vector at a time (cannot combine them), to avoid confusions.

**Comment by davidmyriel** [comment]
Added to doc update roadmap for week of June 11th.
