### ISSUE TITLE
Disambiguate the use of "store"

### ISSUE THREAD

**Issue by agourlay** [qdrant/docs#124]
We use the verb "store" quite extensively in our documentation.

It is however used with different semantics which can be confusing.

e.g. https://qdrant.tech/documentation/storage/#vector-storage

```
In-memory storage - Stores all vectors in RAM, has the highest speed since disk access is required only for persistence.
```  

One way of reading this is that vectors are not persisted on disk, meaning that Qdrant would be an in-memory database.

In reality, vectors are stored on disk and are pre-loaded in RAM at startupfor fast access.

Ideally,  it should be clear to the user whether something is persisted on disk and/or loaded in memory.

**Comment by davidmyriel** [comment]
I will transfer this over to landing_page and make sure terminology applies
