### ISSUE TITLE
Style: impossible to distinguish some links

### ISSUE THREAD

**Issue by timvisee** [qdrant/docs#126]
In the current documentation, it is hard or impossible to distinguish some links.

In alert banners [here](https://qdrant.tech/documentation/security/#authentication):

![image](https://github.com/qdrant/docs/assets/856222/3aaa4aca-9d60-4cea-a864-8db9751e8b3a)
![image](https://github.com/qdrant/docs/assets/856222/a91ce115-01d3-4fc6-b9be-e37b169b72f6)

or:

![image](https://github.com/qdrant/docs/assets/856222/9a550387-3d87-480b-ae8a-c071dd74fa18)
![image](https://github.com/qdrant/docs/assets/856222/6fd6e696-27cd-42de-8c76-1b25e5223c0b)

Or [here](https://qdrant.tech/documentation/security/#tls) where I don't find it immediately clear that `.pem` is a literal and `mkcert` is a clickable link:

![image](https://github.com/qdrant/docs/assets/856222/3ad0e8be-6fea-42b1-bd7b-6b8c5c7fe3c7)

I suggest two changes:

- underline links
- tweak links colors (different link color in banner, different banner text color, or different link color overall)

**Comment by davidmyriel** [comment]
will address in new document repo, thank you
