### ISSUE TITLE
Error in collections.md

### ISSUE THREAD

**Issue by rohan843** [qdrant/docs#68]
Line 11 of the above file (https://github.com/qdrant/docs/blob/master/qdrant/v1.1.x/collections.md) says, "Distance metrics used to measure similarities among vectors."

I believe an 'are' might be required after 'Distance metrics', resulting in: 'Distance metrics _are_ used to measure similarities among vectors.'

**Comment by timvisee** [comment]
Thank you for spotting and reporting this typo!
