### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by juancitotrucupey** [qdrant/docs#81]
I am using the python API version 1.1.1 and I cannot get the name of all the collection with `client.list_aliases()` as exposed here[here](https://github.com/qdrant/docs/blob/f3202268f14d83b04aa325db9bf20dde5b5471bf/qdrant/v1.1.x/collections.md?plain=1#L374-L380).

I need to use `client.get_aliases()` instead.

**Comment by timvisee** [comment]
Thanks for catching and reporting this!

You're totally right, it's called `get_aliases()`: https://github.com/search?q=repo%3Aqdrant%2Fqdrant-client+get_aliases&type=code
